### ISSUE TITLE
Problems with Windows

### ISSUE THREAD

**Issue by dgleich** [JuliaLinearAlgebra/MatrixDepot.jl#106]
Just a quick note that the download command using `sh` and `curl` is causing lots of problems for people who use windows. Even installing MinGW and MSYS2 doesn't seem to fix the issue.

e.g. that will still leave `sh` unresolved on the path as that isn't a standard path addition. 

I imagine there is a good reason to do it this way, but perhaps there could be alternatives?

(Sorry for the sloppier than typical bug report, this is on behalf of the students in my class that use windows and so I've been trying to help them and coming up empty handed...)

**Comment by KlausC** [comment]
@dgleich The new release 1.0.9 should run on windows (and macos) as well. Enjoy!

**Comment by dgleich** [comment]
Thank you!! Really appreciate it :) 

David

**Comment by KlausC** [comment]
I am happy to see, that this package is actively used! 
Your current course reminds me of my own studies on nonlinear optimization in 1978.
Klaus
