### ISSUE TITLE
Remove non-structural zeros

### ISSUE THREAD

**Issue by gdalle** [JuliaLinearAlgebra/MatrixDepot.jl#118]
I just realized that some coefficients are stored even though their value is zero. Is that intended behavior?

```julia
julia> using MatrixDepot, SparseArrays

julia> mat = matrixdepot("Bai/af23560");

julia> nnz(mat)
484256

julia> sum(!iszero, mat)
460598

julia> nnz(dropzeros(mat))
460598
```

**Comment by KlausC** [comment]
`MatrixDepot` reproduces exactly what is found in the database. No editing occurs. `A[8,1]` is a stored zero.

```
%%MatrixMarket matrix coordinate real general
%-------------------------------------------------------------------------------
% UF Sparse Matrix Collection, Tim Davis
% http://www.cise.ufl.edu/research/sparse/matrices/Bai/af23560
% name: Bai/af23560
% [ NACA 0012 AIRFOIL  M=0.8, EIGENVALUE CALCULATION]
% id: 291
% date: 1991
% author: A. Mahajan
% ed: Z. Bai, D. Day, J. Demmel, J. Dongarra
% fields: title A Zeros name id date author ed kind
% kind: computational fluid dynamics problem
%-------------------------------------------------------------------------------
23560 23560 484256
1 1 -41.8292081
5 1 10.0716866
6 1 .094830215
7 1 4.26627159
8 1 0
153 1 17.5548016
```

**Comment by gdalle** [comment]
Good to know. It's a bit surprising though because when you interrogate the database, you get the number of zero values, not the number of structural zeros

![image](https://github.com/JuliaLinearAlgebra/MatrixDepot.jl/assets/22795598/5208a36d-5941-400f-ba5e-e1f8d651affc)

I spent a solid hour wondering what I had done wrong, because the number above is also the one reported in some articles

**Comment by gdalle** [comment]
Perhaps this would be worth documenting?

**Comment by KlausC** [comment]
But that can't be blaming this package, because it can be different in each example.
The correct address is found in the documentation in the published data file (see above).

**Comment by gdalle** [comment]
I'm not blaming anyone here :) Just suggesting to add one line to the README of MatrixDepot.jl, warning users about the difference between structural and accidental nonzeros, so that they don't fall into the same trap as me

**Comment by KlausC** [comment]
@gdalle you are welcome to provide a PR (or a version of `README.md`, so I can do that)
