### ISSUE TITLE
tridiag groups

### ISSUE THREAD

**Issue by AnzhiZhang** [JuliaLinearAlgebra/MatrixDepot.jl#121]
In the document, tridiag is in these groups:

https://github.com/JuliaLinearAlgebra/MatrixDepot.jl/blob/cbfd310c5204dc4a720a770c2c3b8ba4102d6ec7/src/higham.jl#L827

However, in the `data.jl`, tridiag is also in the symmetric group:

https://github.com/JuliaLinearAlgebra/MatrixDepot.jl/blob/cbfd310c5204dc4a720a770c2c3b8ba4102d6ec7/src/data.jl#L51-L56

Is this an inconsistency? Tridiag seems like it should not be in the symmetric group, I can create a PR for it if needed.

**Comment by KlausC** [comment]
You are right, "tridiag" will be removed in "src/data.jl" in the next release.
